export const Products = [
  {
    name: "Caixão para Broxa",
    description: "Para quem não deu conta do recado, vem com alçconstrangimento.",
    price: 899.99,
    quantity: 1,
    category: "Produtos Especiais",
  },
  {
    name: "Óculos de Visão de Raio-X Mentiroso",
    description: "Finalmente, veja tudo que ninguém pediu pana sua imaginação).",
    price: 59.99,
    quantity: 25,
    category: "Acessórios Mágicos",
  },
  {
    name: "Camisa Anti-Sogra",
    description: "Repele comentários ácidos a até 5 metros de dia almoços de domingo.",
    price: 79.90,
    quantity: 100,
    category: "Vestuário",
  },
  {
    name: "Desodorante para Mente Poluída",
    description: "Refresca pensamentos inadequados por até 4enos tenta).",
    price: 19.90,
    quantity: 200,
    category: "Cuidados Pessoais",
  },
  {
    name: "Capa de Invisibilidade para Boletos",
    description: "Torna qualquer conta invisível! Atenção: só visível para o dono.",
    price: 29.90,
    quantity: 300,
    category: "Magia Moderna",
  },
  {
    name: "Almofada Abraço de Carência",
    description: "Para aqueles dias solitários. Mais fofo que qualquer realidade.",
    price: 49.90,
    quantity: 500,
    category: "Conforto",
  },
  {
    name: "Detector de Ex Encrenca",
    description: "Apita quando sente treta chegando. Funciona a até 10 metros de distância.",
    price: 89.90,
    quantity: 75,
    category: "Acessórios Pessoais",
  },
  {
    name: "Tapa-Olho para Conversa Chata",
    description: "Coloque e pronto! Você automaticamente não está mais lá. Acompanha fones de ouvido imaginários.",
    price: 14.90,
    quantity: 150,
    category: "Acessórios Cômicos",
  },
  {
    name: "Colírio Apagador de Desculpas",
    description: "Apague aquela desculpa esfarrapada da sua memória (ou pelo menos tente).",
    price: 24.90,
    quantity: 100,
    category: "Cuidados Especiais",
  },
  {
    name: "Zíper de Boca para Opiniões Não Solicitadas",
    description: "Ajuda a manter as opiniões para si. Útil em jantares e reuniões de família.",
    price: 9.99,
    quantity: 250,
    category: "Controle Pessoal",
  }
];
